# Form implementation generated from reading ui file 'registerpage.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(930, 701)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 930, 701))
        self.widget.setStyleSheet("background-color: rgb(165,213,255);")
        self.widget.setObjectName("widget")
        self.widget_3 = QtWidgets.QWidget(parent=self.widget)
        self.widget_3.setGeometry(QtCore.QRect(20, 20, 891, 661))
        self.widget_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;")
        self.widget_3.setObjectName("widget_3")
        self.txtEmail_2 = QtWidgets.QLineEdit(parent=self.widget_3)
        self.txtEmail_2.setGeometry(QtCore.QRect(40, 500, 391, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(-1)
        self.txtEmail_2.setFont(font)
        self.txtEmail_2.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border: 2px solid rgb(122, 122, 122);\n"
"border-radius: 10px;\n"
"color:rgba(0,0,0,240);\n"
"background-color: rgb(255, 255, 255);\n"
"font-family: \"Tahoma\", sans-serif;\n"
"font-size: 18px;\n"
"")
        self.txtEmail_2.setText("")
        self.txtEmail_2.setObjectName("txtEmail_2")
        self.txtFaculty_2 = QtWidgets.QLineEdit(parent=self.widget_3)
        self.txtFaculty_2.setGeometry(QtCore.QRect(470, 300, 391, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(-1)
        self.txtFaculty_2.setFont(font)
        self.txtFaculty_2.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border: 2px solid rgb(122, 122, 122);\n"
"border-radius: 10px;\n"
"color:rgba(0,0,0,240);\n"
"background-color: rgb(255, 255, 255);\n"
"font-family: \"Tahoma\", sans-serif;\n"
"font-size: 18px;\n"
"")
        self.txtFaculty_2.setText("")
        self.txtFaculty_2.setObjectName("txtFaculty_2")
        self.txtName_2 = QtWidgets.QLineEdit(parent=self.widget_3)
        self.txtName_2.setGeometry(QtCore.QRect(40, 400, 391, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(-1)
        self.txtName_2.setFont(font)
        self.txtName_2.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border: 2px solid rgb(122, 122, 122);\n"
"border-radius: 10px;\n"
"color:rgba(0,0,0,240);\n"
"background-color: rgb(255, 255, 255);\n"
"font-family: \"Tahoma\", sans-serif;\n"
"font-size: 18px;\n"
"")
        self.txtName_2.setText("")
        self.txtName_2.setObjectName("txtName_2")
        self.txtMajor_2 = QtWidgets.QLineEdit(parent=self.widget_3)
        self.txtMajor_2.setGeometry(QtCore.QRect(470, 400, 391, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(-1)
        self.txtMajor_2.setFont(font)
        self.txtMajor_2.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border: 2px solid rgb(122, 122, 122);\n"
"border-radius: 10px;\n"
"color:rgba(0,0,0,240);\n"
"background-color: rgb(255, 255, 255);\n"
"font-family: \"Tahoma\", sans-serif;\n"
"font-size: 18px;\n"
"")
        self.txtMajor_2.setText("")
        self.txtMajor_2.setObjectName("txtMajor_2")
        self.txtStuID_2 = QtWidgets.QLineEdit(parent=self.widget_3)
        self.txtStuID_2.setGeometry(QtCore.QRect(40, 300, 391, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(-1)
        self.txtStuID_2.setFont(font)
        self.txtStuID_2.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border: 2px solid rgb(122, 122, 122);\n"
"border-radius: 10px;\n"
"color:rgba(0,0,0,240);\n"
"background-color: rgb(255, 255, 255);\n"
"font-family: \"Tahoma\", sans-serif;\n"
"font-size: 18px;\n"
"")
        self.txtStuID_2.setText("")
        self.txtStuID_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.txtStuID_2.setObjectName("txtStuID_2")
        self.lblUpAvatar_3 = QtWidgets.QLabel(parent=self.widget_3)
        self.lblUpAvatar_3.setGeometry(QtCore.QRect(110, 190, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lblUpAvatar_3.setFont(font)
        self.lblUpAvatar_3.setStyleSheet("font-family: \"Roboto\", sans-serif;\n"
"font-size: 25px;\n"
"font-weight: bold;\n"
"background-color: transparent;")
        self.lblUpAvatar_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblUpAvatar_3.setObjectName("lblUpAvatar_3")
        self.btnUpAvatar_2 = QtWidgets.QPushButton(parent=self.widget_3)
        self.btnUpAvatar_2.setGeometry(QtCore.QRect(150, 40, 151, 151))
        self.btnUpAvatar_2.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.btnUpAvatar_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(r"Interface\Png\Icon\UploadAvatar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnUpAvatar_2.setIcon(icon)
        self.btnUpAvatar_2.setIconSize(QtCore.QSize(150, 150))
        self.btnUpAvatar_2.setObjectName("btnUpAvatar_2")
        self.txtYear_2 = QtWidgets.QLineEdit(parent=self.widget_3)
        self.txtYear_2.setGeometry(QtCore.QRect(470, 500, 391, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(-1)
        self.txtYear_2.setFont(font)
        self.txtYear_2.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border: 2px solid rgb(122, 122, 122);\n"
"border-radius: 10px;\n"
"color:rgba(0,0,0,240);\n"
"background-color: rgb(255, 255, 255);\n"
"font-family: \"Tahoma\", sans-serif;\n"
"font-size: 18px;\n"
"")
        self.txtYear_2.setText("")
        self.txtYear_2.setObjectName("txtYear_2")
        self.btnResgister_2 = QtWidgets.QPushButton(parent=self.widget_3)
        self.btnResgister_2.setGeometry(QtCore.QRect(690, 590, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnResgister_2.setFont(font)
        self.btnResgister_2.setStyleSheet("background-color: rgb(0, 119, 182);\n"
"border-radius: 20px;\n"
"font-family:Ms Sans Serif Regular;\n"
"font-size:22px;\n"
"color:rgb(255, 255, 255);\n"
"font-family: \"Tahoma\", sans-serif;\n"
"font-size: 22px;\n"
"font-weight:bold;")
        self.btnResgister_2.setObjectName("btnResgister_2")
        self.label_14 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_14.setGeometry(QtCore.QRect(460, 40, 401, 201))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap(r"Interface\Png\Image\register.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.label = QtWidgets.QLabel(parent=self.widget_3)
        self.label.setGeometry(QtCore.QRect(40, 270, 111, 16))
        self.label.setStyleSheet("font-family: \"Roboto\", sans-serif;\n"
"font-size: 18px;\n"
"font-weight: bold;\n"
"background-color: transparent;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_2.setGeometry(QtCore.QRect(40, 370, 111, 16))
        self.label_2.setStyleSheet("font-family: \"Roboto\", sans-serif;\n"
"font-size: 18px;\n"
"font-weight: bold;\n"
"background-color: transparent;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_3.setGeometry(QtCore.QRect(40, 470, 111, 16))
        self.label_3.setStyleSheet("font-family: \"Roboto\", sans-serif;\n"
"font-size: 18px;\n"
"font-weight: bold;\n"
"background-color: transparent;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_4.setGeometry(QtCore.QRect(470, 270, 111, 16))
        self.label_4.setStyleSheet("font-family: \"Roboto\", sans-serif;\n"
"font-size: 18px;\n"
"font-weight: bold;\n"
"background-color: transparent;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_5.setGeometry(QtCore.QRect(470, 370, 111, 16))
        self.label_5.setStyleSheet("font-family: \"Roboto\", sans-serif;\n"
"font-size: 18px;\n"
"font-weight: bold;\n"
"background-color: transparent;")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_6.setGeometry(QtCore.QRect(470, 470, 111, 16))
        self.label_6.setStyleSheet("font-family: \"Roboto\", sans-serif;\n"
"font-size: 18px;\n"
"font-weight: bold;\n"
"background-color: transparent;")
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.txtEmail_2.setPlaceholderText(_translate("MainWindow", "Enter your Email"))
        self.txtFaculty_2.setPlaceholderText(_translate("MainWindow", "Enter your Faculty"))
        self.txtName_2.setPlaceholderText(_translate("MainWindow", "Enter your Name"))
        self.txtMajor_2.setPlaceholderText(_translate("MainWindow", "Enter your Major"))
        self.txtStuID_2.setPlaceholderText(_translate("MainWindow", "Enter your Student ID"))
        self.lblUpAvatar_3.setText(_translate("MainWindow", "Upload your avatar"))
        self.txtYear_2.setPlaceholderText(_translate("MainWindow", "Enter your Year"))
        self.btnResgister_2.setText(_translate("MainWindow", "Register"))
        self.label.setText(_translate("MainWindow", "Student ID:"))
        self.label_2.setText(_translate("MainWindow", "Name:"))
        self.label_3.setText(_translate("MainWindow", "Email:"))
        self.label_4.setText(_translate("MainWindow", "Faculity:"))
        self.label_5.setText(_translate("MainWindow", "Major:"))
        self.label_6.setText(_translate("MainWindow", "Year:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
